
# Gin-Vue-Admin Global Configuration

# jwt configuration
jwt:
  signing-key: 'wxykkkkk'
  expires-time: 604800
  buffer-time: 86400

# system configuration
system:
  env: 'debug'    # debug release
  addr: '127.0.0.1:7010'


# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[study->]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true


# mysql connect configuration
mysql:
  path: '172.16.137.129:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'mini_blog'
  username: 'root'
  password: 'Admin12345-'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false


# redis configuration
redis:
  db: 0
  addr: '172.16.137.129:6379'
  password: 'root12345'
